#!/usr/bin/env Rscript
# -----------------------------------------------------------------------------
# CUT&Tag downstream analysis script aligned with the official workflow
# https://yezhengstat.github.io/CUTTag_tutorial and Henikoff lab guidelines.
#
# This script reads the consensus peak count matrix generated by
# cut_tag_pipeline.sh, performs normalization and differential analysis with
# DESeq2, annotates peaks, and generates essential QC and visualization plots.
#
# Required R packages: tidyverse, DESeq2, tximport, rtracklayer, ChIPseeker,
# clusterProfiler, org.Hs.eg.db (or organism-specific annotation), pheatmap,
# EnhancedVolcano.
# -----------------------------------------------------------------------------

# =========================== 0. LOAD LIBRARIES ===============================
suppressPackageStartupMessages({
  library(tidyverse)
  library(DESeq2)
  library(ChIPseeker)
  library(clusterProfiler)
  library(org.Hs.eg.db)      # Replace with org.Mm.eg.db if working with mouse
  library(TxDb.Hsapiens.UCSC.hg38.knownGene) # Replace with matching TxDb
  library(pheatmap)
  library(EnhancedVolcano)
  library(rtracklayer)
  library(ashr)              # Required for lfcShrink(type = "ashr")
})

# ========================= 1. USER-DEFINED PATHS =============================
# Update the paths below to match the output from cut_tag_pipeline.sh
counts_file <- "/path/to/cut_tag_results/09_counts/consensus_peak_counts.txt"
consensus_bed <- "/path/to/cut_tag_results/08_consensus/consensus_peaks.bed"
output_dir <- "/path/to/cut_tag_results/10_downstream"

dir.create(output_dir, showWarnings = FALSE, recursive = TRUE)

# ========================== 2. SAMPLE METADATA ===============================
# Define sample information. Adjust condition labels to match the experiment.
sample_table <- tibble::tribble(
  ~sample, ~condition, ~replicate,
  "EC1",   "EC",       1,
  "EC2",   "EC",       2,
  "EU1",   "EU",       1
)

# ======================== 3. READ & CLEAN COUNT MATRIX =======================
# featureCounts SAF output contains comment lines starting with '#'.
raw_counts <- read.delim(counts_file, comment.char = "#")

# Convert to matrix and align columns with samples.
count_matrix <- raw_counts %>%
  dplyr::select(dplyr::all_of(sample_table$sample)) %>%
  as.matrix()
rownames(count_matrix) <- raw_counts$Geneid

# Ensure column order matches metadata.
count_matrix <- count_matrix[, sample_table$sample]

# ======================= 4. BUILD DESEQ2 DATASET =============================
coldata <- sample_table %>%
  column_to_rownames("sample")
coldata_df <- as.data.frame(coldata)

dds <- DESeqDataSetFromMatrix(countData = count_matrix,
                              colData = coldata,
                              design = ~ condition)

# Prefilter to remove peaks with low counts.
keep <- rowSums(counts(dds)) >= 10
dds <- dds[keep, ]

# Run DESeq2 normalization and model fitting.
dds <- DESeq(dds)

# Variance-stabilizing transformation for visualization.
dds_vst <- vst(dds, blind = FALSE)

# ========================== 5. QC VISUALIZATIONS =============================
message("Generating PCA plot.")
pca_data <- plotPCA(dds_vst, intgroup = "condition", returnData = TRUE)
pca_percent <- attr(pca_data, "percentVar")

p_pca <- ggplot(pca_data, aes(PC1, PC2, color = condition, label = name)) +
  geom_point(size = 4) +
  geom_text(vjust = 1.5, show.legend = FALSE) +
  labs(x = paste0("PC1: ", round(pca_percent[1] * 100), "%"),
       y = paste0("PC2: ", round(pca_percent[2] * 100), "%"),
       title = "CUT&Tag PCA") +
  theme_bw(base_size = 14)
ggsave(file.path(output_dir, "pca_plot.pdf"), p_pca, width = 6, height = 5)

dists <- dist(t(assay(dds_vst)))
mat <- as.matrix(dists)
pheatmap(mat,
         clustering_distance_rows = dists,
         clustering_distance_cols = dists,
         display_numbers = TRUE,
         main = "Sample-to-sample distance (VST)",
         filename = file.path(output_dir, "sample_distance_heatmap.pdf"))

# ===================== 6. DIFFERENTIAL PEAK ANALYSIS =========================
# Contrast: EC vs EU. Adjust to desired comparisons.
res_ec_vs_eu <- lfcShrink(dds,
                          contrast = c("condition", "EC", "EU"),
                          type = "ashr") %>%
  as.data.frame() %>%
  rownames_to_column("peak_id")

# Save table
readr::write_csv(res_ec_vs_eu, file.path(output_dir, "EC_vs_EU_DESeq2_results.csv"))

# Volcano plot
p_volcano <- EnhancedVolcano(res_ec_vs_eu,
                             lab = res_ec_vs_eu$peak_id,
                             x = "log2FoldChange",
                             y = "padj",
                             pCutoff = 0.05,
                             FCcutoff = 1,
                             title = "EC vs EU differential peaks")
ggsave(file.path(output_dir, "EC_vs_EU_volcano.pdf"), p_volcano, width = 6, height = 5)

# ====================== 7. TOP PEAK HEATMAP ==================================
# Select top 100 differential peaks by adjusted p-value.
top_peaks <- res_ec_vs_eu %>%
  drop_na(padj) %>%
  arrange(padj) %>%
  slice_head(n = 100) %>%
  pull(peak_id)

mat_top <- assay(dds_vst)[top_peaks, ]
pheatmap(mat_top,
         scale = "row",
         clustering_distance_rows = "correlation",
         annotation_col = coldata_df,
         show_rownames = FALSE,
         main = "Top 100 differential peaks",
         filename = file.path(output_dir, "top100_peak_heatmap.pdf"))

# ====================== 8. PEAK ANNOTATION ===================================
# Load peak coordinates and annotate relative to genomic features.
peaks_gr <- rtracklayer::import(con = consensus_bed, format = "BED")

# Ensure peak IDs match the count matrix rownames (peak_N).
peak_ids <- ifelse(is.na(peaks_gr$name) | peaks_gr$name == "",
                   paste0("peak_", seq_along(peaks_gr)),
                   peaks_gr$name)
names(peaks_gr) <- peak_ids
peaks_gr <- peaks_gr[names(peaks_gr) %in% rownames(dds)]

peak_anno <- annotatePeak(peaks_gr,
                          TxDb = TxDb.Hsapiens.UCSC.hg38.knownGene,
                          tssRegion = c(-2000, 2000),
                          annoDb = "org.Hs.eg.db")

peak_anno_df <- as.data.frame(peak_anno)
readr::write_csv(peak_anno_df, file.path(output_dir, "consensus_peak_annotation.csv"))

# Plot annotation distribution
pdf(file.path(output_dir, "peak_annotation_piechart.pdf"), width = 6, height = 6)
plotAnnoPie(peak_anno)
dev.off()

# ====================== 9. ENRICHMENT ANALYSES ===============================
# Gene Ontology enrichment using nearest genes of significant peaks.
sig_peaks <- res_ec_vs_eu %>%
  filter(padj < 0.05, abs(log2FoldChange) >= 1)

sig_genes <- peak_anno_df %>%
  filter(peak %in% sig_peaks$peak_id) %>%
  pull(geneId) %>%
  unique()

if (length(sig_genes) >= 10) {
  ego <- enrichGO(gene = sig_genes,
                  OrgDb = org.Hs.eg.db,
                  keyType = "ENTREZID",
                  ont = "BP",
                  pAdjustMethod = "BH",
                  readable = TRUE)
  pdf(file.path(output_dir, "GO_enrichment.pdf"), width = 8, height = 6)
  print(dotplot(ego, showCategory = 20) + ggtitle("GO BP enrichment"))
  dev.off()
}

# ===================== 10. EXPORT NORMALIZED COUNTS ==========================
normalized_counts <- assay(dds_vst) %>%
  as.data.frame() %>%
  rownames_to_column("peak_id")

readr::write_csv(normalized_counts, file.path(output_dir, "vst_normalized_counts.csv"))

message("Downstream CUT&Tag analysis completed.")
